version: 2
updates:
  # Update Github actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/requirements/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "django"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "celery"
        update-types: ["version-update:semver-major"]
        # flower depends on celery 5
      - dependency-name: "flower"
        update-types: ["version-update:semver-major"]
