version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "django"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "django"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
      - dependency-name: "webpack*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
