version: '3'

volumes:
  local_media_files:
  local_postgres_data:

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: dataskop_local_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
      - local_media_files:/media:z

    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000' # django
      - '8080:8080' # webpack dev live reload
    command: /start
    restart: unless-stopped

  postgres:
    image: postgres:11
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '8025:8025'

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: dataskop_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: dataskop_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: dataskop_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
