version: '3'

volumes:
  local_media_files:
  local_postgres_data:
  local_node_modules:

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: dataskop_local_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
      - local_media_files:/media:z
      # Do make the node-based development tools such as ESlint work
      # we need to have read access to `node`s `node_modules`.
      - local_node_modules:/app/node_modules:z,ro

    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
    restart: unless-stopped

  postgres:
    image: postgres:11
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '8025:8025'

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: dataskop_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: dataskop_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: dataskop_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./docker/local/node/Dockerfile
    image: dataskop_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - local_node_modules:/app/node_modules:z
    command: npm run dev
    ports:
      - '3000:3000'
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - '3001:3001'
