version: "3"

volumes:
  production_postgres_data: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
      args:
        - GPG_PUBLIC_KEY_URL=${GPG_PUBLIC_KEY_URL}
    image: goliath_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    volumes:
      - /var/goliath_backups/:/backups
      - /var/goliath_media_files/:/media

  postgres:
    image: postgres:11
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: goliath_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: goliath_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: goliath_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: goliath_production_flower
    command: /start-flower
