# Generated by Django 3.2.15 on 2022-08-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lookups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookup",
            name="processing",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lookup",
            name="data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
