# Generated by Django 3.2.15 on 2022-08-29 19:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lookups", "0002_auto_20220829_1200"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lookup",
            name="processing",
        ),
        migrations.AlterField(
            model_name="lookup",
            name="data",
            field=models.BinaryField(),
        ),
        migrations.CreateModel(
            name="LookupJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                ("processing", models.BooleanField(default=False)),
                ("error", models.BooleanField(default=False)),
                ("trusted", models.BooleanField(default=False)),
                (
                    "input_todo",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=25),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("input_done", models.JSONField(blank=True, null=True)),
                ("log", models.TextField(default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="lookup",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lookups.lookupjob",
            ),
        ),
    ]
