# Generated by Django 3.2.15 on 2022-08-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0003_auto_20220829_1951"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lookup",
            name="created",
        ),
        migrations.RemoveField(
            model_name="lookup",
            name="modified",
        ),
    ]
