# Generated by Django 3.1.9 on 2021-05-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0002_generic_permissions_index'),
        ('users', '0009_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
