# Generated by Django 3.2.11 on 2022-01-28 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_delete_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
