# Generated by Django 3.2.11 on 2022-01-28 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
