# Generated by Django 3.1.5 on 2021-01-26 13:01

from django.db import migrations, models
import goliath.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210121_1829'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', goliath.users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
