# Generated by Django 3.0.10 on 2020-10-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentmessage',
            name='delievered_at',
        ),
        migrations.AddField(
            model_name='sentmessage',
            name='esp_message_id',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentmessage',
            name='esp_message_status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receivedmessage',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sentmessage',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
