# Generated by Django 3.0.10 on 2020-10-21 12:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0003_auto_20201021_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
