# Generated by Django 3.0.10 on 2020-10-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0004_auto_20201021_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casehandling.Entity'),
        ),
    ]
