# Generated by Django 3.0.10 on 2020-10-21 15:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0005_case_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedmessage',
            name='cc_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='from_display_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='from_display_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='spam_score',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='to_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
