# Generated by Django 3.0.10 on 2020-10-29 16:20

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0011_historicalcase_historicalentity_historicalreceivedmessage_historicalsentmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalentity',
            name='history_user',
        ),
        migrations.AddField(
            model_name='casetype',
            name='_description_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='casetype',
            name='description_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='entity',
            name='_description_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='description_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='description',
            field=markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True),
        ),
        migrations.DeleteModel(
            name='HistoricalCaseType',
        ),
        migrations.DeleteModel(
            name='HistoricalEntity',
        ),
    ]
