# Generated by Django 3.0.10 on 2020-10-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0012_auto_20201029_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
