# Generated by Django 3.0.10 on 2020-11-02 13:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0015_historicalcasetype_historicalentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetype',
            name='questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text="Please go to https://surveyjs.io/create-survey and paste the JSON 'JSON Editor'. Then go to 'Survey Designer' to edit the survey. Try it out with 'Test Survey'. When you are done, paste the JSON in this field and hit save."),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text="Please go to https://surveyjs.io/create-survey and paste the JSON 'JSON Editor'. Then go to 'Survey Designer' to edit the survey. Try it out with 'Test Survey'. When you are done, paste the JSON in this field and hit save."),
        ),
    ]
