# Generated by Django 3.1.5 on 2021-01-11 14:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0017_auto_20210107_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsupport',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='answers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='questions',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='questions',
            field=models.JSONField(help_text="Please go to https://surveyjs.io/create-survey and paste the JSON 'JSON Editor'. Then go to 'Survey Designer' to edit the survey. Try it out with 'Test Survey'. When you are done, paste the JSON in this field and hit save."),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='answers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='questions',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='questions',
            field=models.JSONField(help_text="Please go to https://surveyjs.io/create-survey and paste the JSON 'JSON Editor'. Then go to 'Survey Designer' to edit the survey. Try it out with 'Test Survey'. When you are done, paste the JSON in this field and hit save."),
        ),
        migrations.AddIndex(
            model_name='externalsupport',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='casehandlin_search__f470e6_gin'),
        ),
    ]
