# Generated by Django 3.1.5 on 2021-02-01 14:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casehandling', '0021_auto_20210128_2309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalMessageReceived',
            new_name='HistoricalReceivedMessage',
        ),
        migrations.RenameModel(
            old_name='HistoricalMessageSent',
            new_name='HistoricalSentMessage',
        ),
        migrations.RenameModel(
            old_name='MessageReceived',
            new_name='ReceivedMessage',
        ),
        migrations.RenameModel(
            old_name='MessageSent',
            new_name='SentMessage',
        ),
        migrations.AlterModelOptions(
            name='historicalreceivedmessage',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical received message'},
        ),
        migrations.AlterModelOptions(
            name='historicalsentmessage',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sent message'},
        ),
    ]
