# Generated by Django 3.1.5 on 2021-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0023_goliathflatpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='casetype',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='historicalcasetype',
            name='entity',
        ),
        migrations.AddField(
            model_name='case',
            name='selected_entities',
            field=models.ManyToManyField(blank=True, null=True, to='casehandling.Entity'),
        ),
        migrations.AddField(
            model_name='casetype',
            name='entities',
            field=models.ManyToManyField(blank=True, null=True, to='casehandling.Entity'),
        ),
    ]
