# Generated by Django 3.1.5 on 2021-02-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0024_auto_20210203_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='selected_entities',
            field=models.ManyToManyField(to='casehandling.Entity'),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='entities',
            field=models.ManyToManyField(to='casehandling.Entity'),
        ),
    ]
