# Generated by Django 3.1.5 on 2021-02-03 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casehandling', '0025_auto_20210203_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casetype',
            name='needs_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='needs_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('EE', 'There was error with sending the email'), ('UV', 'Waiting user verification'), ('CV', 'Waiting until an admin verified the case'), ('ES', 'Waiting until initial email sent'), ('WR', 'Waiting for response'), ('WU', 'Waiting for user input'), ('CN', 'Closed, given up'), ('CP', 'Closed, case resolved'), ('CM', 'Closed, mixed feelings')], max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='status',
            field=models.CharField(choices=[('EE', 'There was error with sending the email'), ('UV', 'Waiting user verification'), ('CV', 'Waiting until an admin verified the case'), ('ES', 'Waiting until initial email sent'), ('WR', 'Waiting for response'), ('WU', 'Waiting for user input'), ('CN', 'Closed, given up'), ('CP', 'Closed, case resolved'), ('CM', 'Closed, mixed feelings')], max_length=2),
        ),
    ]
