# Generated by Django 3.1.5 on 2021-02-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0027_auto_20210203_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoreplyKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_caseinsensitiv', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='historicalreceivedmessage',
            name='is_autoreplay',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalreceivedmessage',
            name='parsed_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='is_autoreplay',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='parsed_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetype',
            name='autoreply_keywords',
            field=models.ManyToManyField(to='casehandling.AutoreplyKeyword'),
        ),
    ]
