# Generated by Django 3.1.5 on 2021-02-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0029_auto_20210208_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='sent_reminders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='sent_reminders',
            field=models.IntegerField(default=0),
        ),
    ]
