# Generated by Django 3.1.5 on 2021-02-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0030_auto_20210209_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='selected_entities',
            field=models.ManyToManyField(blank=True, to='casehandling.Entity'),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='autoreply_keywords',
            field=models.ManyToManyField(blank=True, to='casehandling.AutoreplyKeyword'),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='entities',
            field=models.ManyToManyField(blank=True, to='casehandling.Entity'),
        ),
    ]
