# Generated by Django 3.1.5 on 2021-02-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0031_auto_20210210_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetype',
            name='icon_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetype',
            name='order',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='icon_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='order',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
