# Generated by Django 3.1.5 on 2021-02-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0034_casetype_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_contactable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kontaktirbar'),
        ),
        migrations.AddField(
            model_name='case',
            name='post_creation_hint',
            field=models.TextField(blank=True, null=True, verbose_name='Hinweis'),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='is_contactable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kontaktirbar'),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='post_creation_hint',
            field=models.TextField(blank=True, null=True, verbose_name='Hinweis'),
        ),
    ]
