# Generated by Django 3.1.5 on 2021-02-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0036_auto_20210217_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='is_contactable',
            field=models.BooleanField(default=False, verbose_name='Kontaktierbar'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='is_contactable',
            field=models.BooleanField(default=False, verbose_name='Kontaktierbar'),
        ),
    ]
