# Generated by Django 3.1.5 on 2021-02-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0037_auto_20210219_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='last_entities_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='sent_entities_reminders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='last_entities_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='sent_entities_reminders',
            field=models.IntegerField(default=0),
        ),
    ]
