# Generated by Django 3.1.5 on 2021-02-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0038_auto_20210219_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalcasetype',
            name='name',
        ),
        migrations.AddField(
            model_name='casetype',
            name='claim',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='casetype',
            name='short_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='casetype',
            name='title',
            field=models.CharField(default='changethistitle', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='claim',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='short_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='title',
            field=models.CharField(default='changethistitle', max_length=50),
            preserve_default=False,
        ),
    ]
