# Generated by Django 3.1.5 on 2021-02-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0039_auto_20210219_1727'),
        ('casehandling', '0037_auto_20210219_1610'),
    ]

    operations = [
    ]
