# Generated by Django 3.1.5 on 2021-02-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0040_merge_20210219_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='is_contactable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kontaktierbar'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='is_contactable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kontaktierbar'),
        ),
    ]
