# Generated by Django 3.1.5 on 2021-02-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0041_auto_20210219_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='is_contactable',
            field=models.BooleanField(default=False, verbose_name='Kontaktierbar'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='is_contactable',
            field=models.BooleanField(default=False, verbose_name='Kontaktierbar'),
        ),
        migrations.CreateModel(
            name='MultiCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.ManyToManyField(blank=True, to='casehandling.Case')),
            ],
        ),
    ]
