# Generated by Django 3.1.5 on 2021-02-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0042_auto_20210219_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetype',
            name='claim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='claim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
