# Generated by Django 3.1.5 on 2021-02-22 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casehandling', '0043_auto_20210219_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCaseCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_contactable', models.BooleanField(default=False, verbose_name='Kontaktierbar')),
                ('post_creation_hint', models.TextField(blank=True, null=True, verbose_name='Hinweis')),
                ('case_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casehandling.casetype')),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='is_contactable',
        ),
        migrations.RemoveField(
            model_name='case',
            name='post_creation_hint',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='is_contactable',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='post_creation_hint',
        ),
        migrations.DeleteModel(
            name='MultiCase',
        ),
        migrations.AddField(
            model_name='postcasecreation',
            name='cases',
            field=models.ManyToManyField(blank=True, to='casehandling.Case'),
        ),
        migrations.AddField(
            model_name='postcasecreation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
