# Generated by Django 3.1.5 on 2021-02-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0044_auto_20210222_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcasecreation',
            name='cases',
        ),
        migrations.AddField(
            model_name='case',
            name='post_cc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='casehandling.postcasecreation'),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='post_cc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='casehandling.postcasecreation'),
        ),
        migrations.AddField(
            model_name='postcasecreation',
            name='sent_initial_emails_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
