# Generated by Django 3.1.5 on 2021-02-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0045_auto_20210222_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReplyChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='answers_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casetype',
            name='letter_subject_custom_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casetype',
            name='user_notification_custom_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='answers_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='letter_subject_custom_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='user_notification_custom_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
