# Generated by Django 3.1.5 on 2021-02-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0047_auto_20210223_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casetype',
            old_name='user_notification_custom_text',
            new_name='user_notification_new_answer_custom_text',
        ),
        migrations.RenameField(
            model_name='historicalcasetype',
            old_name='user_notification_custom_text',
            new_name='user_notification_new_answer_custom_text',
        ),
        migrations.AddField(
            model_name='casetype',
            name='entity_notification_reminder_custom_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casetype',
            name='user_notification_entity_notification_reminder_custom_text',
            field=models.TextField(blank=True, help_text='Welche Notiz sollen die User erhalten, wenn das Unternehmen erinnert wird zu antworten?', null=True),
        ),
        migrations.AddField(
            model_name='casetype',
            name='user_notification_reminder_custom_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='entity_notification_reminder_custom_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='user_notification_entity_notification_reminder_custom_text',
            field=models.TextField(blank=True, help_text='Welche Notiz sollen die User erhalten, wenn das Unternehmen erinnert wird zu antworten?', null=True),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='user_notification_reminder_custom_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsentmessage',
            name='last_content',
            field=models.TextField(default='fake'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentmessage',
            name='last_content',
            field=models.TextField(default='fake'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('EE', 'Fehler beim E-Mail-Versandt'), ('UV', 'Warten auf User-Verifizierung'), ('CA', 'Warte auf Admin-Approval'), ('ES', 'E-Mail wird versendet'), ('WR', 'Warten auf Antwort'), ('WU', 'Handlung erforderlich'), ('CN', 'Abgeschlossen'), ('CP', 'Abgeschlossen'), ('CM', 'Abgeschlossen')], max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='status',
            field=models.CharField(choices=[('EE', 'Fehler beim E-Mail-Versandt'), ('UV', 'Warten auf User-Verifizierung'), ('CA', 'Warte auf Admin-Approval'), ('ES', 'E-Mail wird versendet'), ('WR', 'Warten auf Antwort'), ('WU', 'Handlung erforderlich'), ('CN', 'Abgeschlossen'), ('CP', 'Abgeschlossen'), ('CM', 'Abgeschlossen')], max_length=2),
        ),
    ]
