# Generated by Django 3.1.5 on 2021-02-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0048_auto_20210224_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetype',
            name='auto_reply_subject',
            field=models.CharField(default='subjectchangeme', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetype',
            name='auto_reply_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='auto_reply_subject',
            field=models.CharField(default='subjectchangeme', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='auto_reply_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
