# Generated by Django 3.1.5 on 2021-03-09 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0050_publicfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='goliathflatpage',
            name='social_media_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goliathflatpage',
            name='social_media_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casehandling.publicfile'),
        ),
    ]
