# Generated by Django 3.1.5 on 2021-03-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0053_receivedattachments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceivedAttachments',
            new_name='ReceivedAttachment',
        ),
    ]
