# Generated by Django 3.1.5 on 2021-03-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0055_auto_20210315_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetype',
            name='auto_reply_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='auto_reply_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
