# Generated by Django 3.1.5 on 2021-03-22 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0057_auto_20210322_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casetype',
            old_name='max_entity_reminder',
            new_name='entity_reminder_max',
        ),
        migrations.RenameField(
            model_name='historicalcasetype',
            old_name='max_entity_reminder',
            new_name='entity_reminder_max',
        ),
        migrations.RemoveField(
            model_name='casetype',
            name='max_user_reminder',
        ),
        migrations.RemoveField(
            model_name='historicalcasetype',
            name='max_user_reminder',
        ),
        migrations.AddField(
            model_name='casetype',
            name='entity_reminder_margin',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AddField(
            model_name='casetype',
            name='user_reminder_margin',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AddField(
            model_name='casetype',
            name='user_reminder_max',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='entity_reminder_margin',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='user_reminder_margin',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='user_reminder_max',
            field=models.IntegerField(default=2),
        ),
    ]
