# Generated by Django 3.1.5 on 2021-03-22 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0058_auto_20210322_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetype',
            name='entity_reminder_margin',
            field=models.DurationField(default=datetime.timedelta(days=7), help_text='Format: DAYS HOURS:MINUTES:SECONDS e.g. for 7 days: `7 00:00:00`, for every minute `00:01:00`'),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='entity_reminder_max',
            field=models.IntegerField(default=2, help_text='Remind X times and then stop'),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='user_reminder_margin',
            field=models.DurationField(default=datetime.timedelta(days=7), help_text='Format: DAYS HOURS:MINUTES:SECONDS e.g. for 7 days: `7 00:00:00`, for every minute `00:01:00`'),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='user_reminder_max',
            field=models.IntegerField(default=2, help_text='Remind X times and then stop'),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='entity_reminder_margin',
            field=models.DurationField(default=datetime.timedelta(days=7), help_text='Format: DAYS HOURS:MINUTES:SECONDS e.g. for 7 days: `7 00:00:00`, for every minute `00:01:00`'),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='entity_reminder_max',
            field=models.IntegerField(default=2, help_text='Remind X times and then stop'),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='user_reminder_margin',
            field=models.DurationField(default=datetime.timedelta(days=7), help_text='Format: DAYS HOURS:MINUTES:SECONDS e.g. for 7 days: `7 00:00:00`, for every minute `00:01:00`'),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='user_reminder_max',
            field=models.IntegerField(default=2, help_text='Remind X times and then stop'),
        ),
    ]
