# Generated by Django 3.1.5 on 2021-03-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0059_auto_20210322_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetype',
            name='description_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='goliathflatpage',
            name='markdown_content_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='description_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='description_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalgoliathflatpage',
            name='markdown_content_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
    ]
