# Generated by Django 3.1.5 on 2021-03-22 17:19

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0060_auto_20210322_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetype',
            name='description',
            field=markupfield.fields.MarkupField(blank=True, help_text='Markdown is available', null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Font Awesome Icon Names', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='order',
            field=models.FloatField(blank=True, help_text='If not null, show this casetype on the front page. In order of this value.', null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=markupfield.fields.MarkupField(blank=True, help_text='Markdown is available', null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='description',
            field=markupfield.fields.MarkupField(blank=True, help_text='Markdown is available', null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Font Awesome Icon Names', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='order',
            field=models.FloatField(blank=True, help_text='If not null, show this casetype on the front page. In order of this value.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='description',
            field=markupfield.fields.MarkupField(blank=True, help_text='Markdown is available', null=True, rendered_field=True),
        ),
    ]
