# Generated by Django 3.1.5 on 2021-03-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0061_auto_20210322_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetype',
            name='auto_reply_subject',
            field=models.CharField(blank=True, help_text='user reply subject to the entity', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='auto_reply_text',
            field=models.TextField(blank=True, help_text='user reply text to the entity', null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='entity_notification_reminder_custom_text',
            field=models.TextField(blank=True, help_text='special text for the entity notification email', null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='letter_subject_custom_template',
            field=models.TextField(blank=True, help_text='subject (django template) initial email sent to the entities', null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='letter_template',
            field=models.TextField(blank=True, help_text='context/body/text (django template) initial email sent to the entities', null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='user_notification_entity_notification_reminder_custom_text',
            field=models.TextField(blank=True, help_text='What note should users receive when the entity is reminded to respond?', null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='user_notification_new_answer_custom_text',
            field=models.TextField(blank=True, help_text='special text for the noficiation email if the entity answered', null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='user_notification_reminder_custom_text',
            field=models.TextField(blank=True, help_text='special text for the reminder email if the user has to choose a status', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='auto_reply_subject',
            field=models.CharField(blank=True, help_text='user reply subject to the entity', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='auto_reply_text',
            field=models.TextField(blank=True, help_text='user reply text to the entity', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='entity_notification_reminder_custom_text',
            field=models.TextField(blank=True, help_text='special text for the entity notification email', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='letter_subject_custom_template',
            field=models.TextField(blank=True, help_text='subject (django template) initial email sent to the entities', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='letter_template',
            field=models.TextField(blank=True, help_text='context/body/text (django template) initial email sent to the entities', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='user_notification_entity_notification_reminder_custom_text',
            field=models.TextField(blank=True, help_text='What note should users receive when the entity is reminded to respond?', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='user_notification_new_answer_custom_text',
            field=models.TextField(blank=True, help_text='special text for the noficiation email if the entity answered', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='user_notification_reminder_custom_text',
            field=models.TextField(blank=True, help_text='special text for the reminder email if the user has to choose a status', null=True),
        ),
    ]
