# Generated by Django 3.1.5 on 2021-04-12 14:36

import django.contrib.postgres.search
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0062_auto_20210322_1747'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='casetype',
            managers=[
                ('search', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='externalsupport',
            managers=[
                ('search', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='casetype',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
