# Generated by Django 3.1.5 on 2021-04-12 14:53

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0063_auto_20210412_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetype',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalsupport',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
