# Generated by Django 3.1.5 on 2021-04-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0064_auto_20210412_1453'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='externalsupport',
            managers=[
            ],
        ),
    ]
