# Generated by Django 3.1.8 on 2021-04-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0065_auto_20210412_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetype',
            name='auto_reply_subject',
            field=models.CharField(default='Bitte um Antwort ', help_text='user reply subject to the entity', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='auto_reply_text',
            field=models.TextField(default='herzlichen Dank für Ihre Mail. Leider beantwortet diese meine Frage nicht. Bisherige Versuche, das Problem über andere Formulare, FAQs oder Hilfe-Foren zu lösen, haben leider nicht zum Erfolg geführt.\n\nIch möchte Sie daher bitten, mir eine*n direkte*n Ansprechpartner*in zu vermitteln.\n', help_text='user reply text to the entity', null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='entity_notification_reminder_custom_text',
            field=models.TextField(default='Bisher habe ich leider keine Antwort erhalten. Ich freue mich über eine zeitnahe Rückmeldung.', help_text='special text for the entity notification email', null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='questions',
            field=models.JSONField(help_text="Please go to https://surveyjs.io/create-survey and paste the JSON 'JSON Editor'.\n        Then go to 'Survey Designer' to edit the survey.Try it out with 'Test Survey'.\n        When you are done, paste the JSON in this field and hit save."),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='user_notification_entity_notification_reminder_custom_text',
            field=models.TextField(default='daran erinnert, dass Sie bisher noch keine Antwort auf ihre Fallmeldung erhalten haben. Bei neuen Entwicklungen benachrichtigen wir Sie per E-Mail.', help_text='What note should users receive when the entity is reminded to respond?', null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='user_notification_new_answer_custom_text',
            field=models.TextField(default='auf Ihre Fallmeldung erhalten. Schau Sie nach, ob sich Ihr Anliegen damit gelöst hat oder ob Sie weitere Schritte einleiten wollen.', help_text='special text for the noficiation email if the entity answered', null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='user_notification_reminder_custom_text',
            field=models.TextField(default='auf Ihre Fallmeldung erhalten, die Sie jetzt bewerten können. Lassen Sie uns wissen, wie zufrieden Sie mit der Reaktion sind.', help_text='special text for the reminder email if the user has to choose a status', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='auto_reply_subject',
            field=models.CharField(default='Bitte um Antwort ', help_text='user reply subject to the entity', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='auto_reply_text',
            field=models.TextField(default='herzlichen Dank für Ihre Mail. Leider beantwortet diese meine Frage nicht. Bisherige Versuche, das Problem über andere Formulare, FAQs oder Hilfe-Foren zu lösen, haben leider nicht zum Erfolg geführt.\n\nIch möchte Sie daher bitten, mir eine*n direkte*n Ansprechpartner*in zu vermitteln.\n', help_text='user reply text to the entity', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='entity_notification_reminder_custom_text',
            field=models.TextField(default='Bisher habe ich leider keine Antwort erhalten. Ich freue mich über eine zeitnahe Rückmeldung.', help_text='special text for the entity notification email', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='questions',
            field=models.JSONField(help_text="Please go to https://surveyjs.io/create-survey and paste the JSON 'JSON Editor'.\n        Then go to 'Survey Designer' to edit the survey.Try it out with 'Test Survey'.\n        When you are done, paste the JSON in this field and hit save."),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='user_notification_entity_notification_reminder_custom_text',
            field=models.TextField(default='daran erinnert, dass Sie bisher noch keine Antwort auf ihre Fallmeldung erhalten haben. Bei neuen Entwicklungen benachrichtigen wir Sie per E-Mail.', help_text='What note should users receive when the entity is reminded to respond?', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='user_notification_new_answer_custom_text',
            field=models.TextField(default='auf Ihre Fallmeldung erhalten. Schau Sie nach, ob sich Ihr Anliegen damit gelöst hat oder ob Sie weitere Schritte einleiten wollen.', help_text='special text for the noficiation email if the entity answered', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='user_notification_reminder_custom_text',
            field=models.TextField(default='auf Ihre Fallmeldung erhalten, die Sie jetzt bewerten können. Lassen Sie uns wissen, wie zufrieden Sie mit der Reaktion sind.', help_text='special text for the reminder email if the user has to choose a status', null=True),
        ),
    ]
