# Generated by Django 3.2.15 on 2022-11-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailjetsync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscription",
            name="has_donated",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
