# Generated by Django 3.2.18 on 2023-02-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailjetsync", "0003_auto_20221109_1832"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscription",
            name="confirmed_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
