name: CI tests

# Enable Buildkit and let compose use it to speed up image building.
# Not working with the caching right now. Thus, it's disabled. (https://github.com/satackey/action-docker-layer-caching/issues/117)
# env:
#   DOCKER_BUILDKIT: 1
#   COMPOSE_DOCKER_CLI_BUILD: 1

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["main"]
    paths-ignore: ["docs/**"]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2.3.5

      - name: Setup ENV files
        run: cp -r docs/exampleenv .envs

      - name: Pull depending docker images
        run: docker-compose -f docker-compose.local.yml pull postgres redis

      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build the stack
        run: docker-compose -f docker-compose.local.yml build django

      - name: Migrate and run tests
        run: docker-compose -f docker-compose.local.yml run django bash -c "./manage.py migrate && pytest"
