name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["main"]
    paths-ignore: ["docs/**"]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2.3.4

      - name: setup ENV files
        run: mkdir .envs && cp -r docs/exampleenv .envs/.local/

      - name: Build the Stack
        run: docker-compose -f docker-compose.local.yml build

      - name: Make DB Migrations
        run: docker-compose -f docker-compose.local.yml run --rm django python manage.py migrate

      - name: Run the Stack
        run: docker-compose -f docker-compose.local.yml up -d

      - name: Run Django Tests
        run: docker-compose -f docker-compose.local.yml run --rm django pytest

      - name: Tear down the Stack
        run: docker-compose -f docker-compose.local.yml down
