name: npm audit fix

on:
  workflow_dispatch:
  schedule:
    - cron: "1 1 * * 1"

jobs:
  npm-audit-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: NPM Audit
        uses: luisfontes19/npm-audit-action@v0.1.0
        with:
          fix: true
          force: false
          git-pr-title: "Bump node dependencies via `npm audit fix`"
          git-message: "Bump node dependencies via `npm audit fix`"
          git-branch: "npm-audit-action-${{ github.run_number }}"
          github-token: ${{ secrets.GH_TOKEN }}
