name: npm audit fix

on:
  workflow_dispatch:
  schedule:
    - cron: "1 1 * * 1"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - uses: ybiquitous/npm-audit-fix-action@v3
        with:
          commit_title: "Bump node dependencies via `npm audit fix`"
