name: prod

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2.3.4

      - name: Build the image
        run: docker build -t dataskop-prod .

      - name: Create a container
        run: docker create -ti --name dataskop-prod-container dataskop-prod bash

      - name: Extract app folder
        run: docker cp dataskop-prod-container:/app prodapp

      - name: Compress
        run: tar -czvf app-${{ github.sha }}.tar.gz prodapp

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.sha }}
          tag_name: deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Upload Tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app-${{ github.sha }}.tar.gz
          asset_name: dataskop-platform.tar.gz
          asset_content_type: application/gzip
          
      - uses: actions/upload-artifact@v2
        with:
          name: dataskop-platform-${{ github.sha }}
          path: app-${{ github.sha }}.tar.gz
