name: prod

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2.3.4

      - name: Build the image
        run: docker build -t dataskop-prod .

      - name: Create an image
        run: docker create -ti --name dataskop-prod-container dataskop-prod bash

      - name: Extract app folder
        run: docker cp dataskop-prod-container:/app prodapp

      - name: compress
        run: tar -czvf prodapp.tar.gz prodapp && echo $(du -h prodapp.tar.gz)
