name: prod

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2.3.4

      - name: Build the image
        run: docker build -t dataskop-prod .

      - name: Create a container
        run: docker create -ti --name dataskop-prod-container dataskop-prod bash

      - name: Extract app folder
        run: docker cp dataskop-prod-container:/app prodapp

      - name: Compress
        run: tar -czvf app-${{ github.sha }}.tar.gz prodapp

      - uses: actions/upload-artifact@v2
        with:
          name: dataskop-platform-${{ github.sha }}
          path: app-${{ github.sha }}.tar.gz
