# Generated by Django 3.1.9 on 2021-05-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="unauthorized_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
