# Generated by Django 3.1.13 on 2021-10-19 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0010_donornotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donornotification",
            name="campaign",
            field=models.ForeignKey(
                help_text="Which campaign should receive this message?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="donornotification",
            name="draft",
            field=models.BooleanField(
                default=True,
                help_text="If you set draft to false, the email will get sent to the chosen campaign (and can't be changed anymore).",
            ),
        ),
        migrations.AlterField(
            model_name="donornotification",
            name="sent_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
