# Generated by Django 3.2.12 on 2022-02-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        (
            "campaigns",
            "0012_auto_20220209_1804_squashed_0013_alter_donornotification_draft",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="site",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaign",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
    ]
