# Generated by Django 3.2.12 on 2022-02-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0015_auto_20220222_1517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteextended",
            name="from_email",
            field=models.EmailField(default="info@example.com", max_length=255),
        ),
        migrations.AlterField(
            model_name="siteextended",
            name="support_email",
            field=models.EmailField(default="support@example.com", max_length=255),
        ),
    ]
