# Generated by Django 3.2.13 on 2022-04-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0018_fix_event_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="accept_new_donations",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalcampaign",
            name="accept_new_donations",
            field=models.BooleanField(default=True),
        ),
    ]
