# Generated by Django 3.2.13 on 2022-05-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0019_auto_20220422_1512"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalcampaign",
            name="featured",
            field=models.BooleanField(default=True),
        ),
    ]
