# Generated by Django 3.2.15 on 2022-08-30 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0021_auto_20220825_0947"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={},
        ),
    ]
