# Generated by Django 3.2.15 on 2022-11-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0022_alter_campaign_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
