# Generated by Django 3.2.18 on 2023-02-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0023_donation_confirmed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="confirmed_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
