# Generated by Django 3.2.18 on 2023-03-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0024_donation_confirmed_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="scraping_config_schema",
            field=models.JSONField(
                blank=True,
                help_text="Optional JSON schema to validate the `config` of `Campaign`",
                null=True,
            ),
        ),
    ]
